[phases.setup]
nixPkgs = [
    "python311",
    "tesseract",
    "tesseract-data-eng"
]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r requirements.txt",
    "playwright install webkit --with-deps"
]

[start]
cmd = "python main.py"