[phases.setup]
nixPkgs = [
    "python311",
    "tesseract",
    "chromium"
]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r requirements.txt",
    "playwright install chromium"
]

[start]
cmd = "python main.py"